// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBTl8ossrge0HKflERpj9hQWNaSzfrick',
    appId: '1:545063521125:web:00805b6b9ddae10cb12f8c',
    messagingSenderId: '545063521125',
    projectId: 'housing-portal-77cc6',
    authDomain: 'housing-portal-77cc6.firebaseapp.com',
    databaseURL: 'https://housing-portal-77cc6-default-rtdb.firebaseio.com',
    storageBucket: 'housing-portal-77cc6.firebasestorage.app',
    measurementId: 'G-GHQLCHDP8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqE7QxUdGXqwsRfnifsukcJOdCDiTFaME',
    appId: '1:545063521125:android:48f9335607189f76b12f8c',
    messagingSenderId: '545063521125',
    projectId: 'housing-portal-77cc6',
    databaseURL: 'https://housing-portal-77cc6-default-rtdb.firebaseio.com',
    storageBucket: 'housing-portal-77cc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAosdhMaOyDOFgWUDJOBeSqCV-sLYJpuZ8',
    appId: '1:545063521125:ios:7051a56fbb7f0a9bb12f8c',
    messagingSenderId: '545063521125',
    projectId: 'housing-portal-77cc6',
    databaseURL: 'https://housing-portal-77cc6-default-rtdb.firebaseio.com',
    storageBucket: 'housing-portal-77cc6.firebasestorage.app',
    iosBundleId: 'com.SAAD.housingPortalPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAosdhMaOyDOFgWUDJOBeSqCV-sLYJpuZ8',
    appId: '1:545063521125:ios:7051a56fbb7f0a9bb12f8c',
    messagingSenderId: '545063521125',
    projectId: 'housing-portal-77cc6',
    databaseURL: 'https://housing-portal-77cc6-default-rtdb.firebaseio.com',
    storageBucket: 'housing-portal-77cc6.firebasestorage.app',
    iosBundleId: 'com.SAAD.housingPortalPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBTl8ossrge0HKflERpj9hQWNaSzfrick',
    appId: '1:545063521125:web:b906d641e7c6d169b12f8c',
    messagingSenderId: '545063521125',
    projectId: 'housing-portal-77cc6',
    authDomain: 'housing-portal-77cc6.firebaseapp.com',
    databaseURL: 'https://housing-portal-77cc6-default-rtdb.firebaseio.com',
    storageBucket: 'housing-portal-77cc6.firebasestorage.app',
    measurementId: 'G-ZVN25M8V35',
  );

}